# Generated by Django 2.2.5 on 2020-10-15 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PubType', models.CharField(choices=[('Journal article', 'Journal article'), ('Pre-print', 'Pre-print'), ('WEB', 'Website'), ('REP', 'Government report'), ('NGO', 'NGO report'), ('OTH', 'Other')], max_length=255, verbose_name='Publication type')),
                ('Author', models.CharField(help_text='surname of lead author (if article)', max_length=255, verbose_name='Author or publisher')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('Date_published', models.DateField(blank=True, help_text='yyyy-mm-dd', verbose_name='Date published')),
                ('Country', models.CharField(blank=True, choices=[('United States', 'United States'), ('South Africa', 'South Africa'), ('Uganda', 'Uganda'), ('Zimbabwe', 'Zimbabwe')], max_length=255, verbose_name='Country / Setting')),
                ('URL', models.URLField(blank=True, verbose_name='URL')),
                ('DOI', models.CharField(blank=True, max_length=255)),
                ('PMID', models.CharField(blank=True, max_length=255)),
                ('hard_copy', models.FileField(blank=True, upload_to='hardcopies/', verbose_name='Saved copy of file')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasource_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasource_modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('input_filepath', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('derivation_documentation', models.FileField(blank=True, upload_to='derivations/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='param_creator', to=settings.AUTH_USER_MODEL)),
                ('data_sources', models.ManyToManyField(blank=True, related_name='param_data', to='parameters.DataSource')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='param_modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abstract', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_user', to=settings.AUTH_USER_MODEL)),
                ('data_sources', models.ManyToManyField(blank=True, related_name='project_data', to='parameters.DataSource')),
                ('parameters', models.ManyToManyField(blank=True, related_name='project_param', to='parameters.Parameter')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='param_project', to='parameters.Project'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='data_param', to='parameters.Parameter'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='data_project', to='parameters.Project'),
        ),
    ]
