# Generated by Django 2.2.5 on 2020-10-08 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('DatePublished', models.DateField(blank=True)),
                ('Country', models.CharField(blank=True, choices=[('US', 'United States'), ('ZA', 'South Africa'), ('UG', 'Uganda'), ('ZW', 'Zimbabwe')], max_length=255)),
                ('URL', models.URLField(blank=True)),
                ('DOI', models.CharField(blank=True, max_length=255)),
                ('PMID', models.CharField(blank=True, max_length=255)),
                ('hard_copy', models.FileField(blank=True, upload_to='hardcopies/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abstract', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('input_filepath', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('derivation_documentation', models.FileField(blank=True, upload_to='derivations/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='param_user', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ManyToManyField(blank=True, related_name='param_data', to='parameters.DataSource')),
                ('project', models.ManyToManyField(blank=True, related_name='param_project', to='parameters.DataSource')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='params',
            field=models.ManyToManyField(blank=True, related_name='data_param', to='parameters.Parameter'),
        ),
    ]
