# Generated by Django 2.2.5 on 2020-10-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='PubType',
            field=models.CharField(choices=[('Journal article', 'Journal article'), ('Pre-print', 'Pre-print'), ('Website', 'Website'), ('Government report', 'Government report'), ('NGO report', 'NGO report'), ('Other', 'Other')], max_length=255, verbose_name='Publication type'),
        ),
    ]
