# Generated by Django 2.2.5 on 2020-10-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='params',
        ),
        migrations.AddField(
            model_name='datasource',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='data_project', to='parameters.Project'),
        ),
    ]
