# Generated by Django 2.2.5 on 2020-10-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_auto_20201008_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='ISBN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datasource',
            name='arXivID',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datasource',
            name='params',
            field=models.ManyToManyField(blank=True, related_name='data_param', to='parameters.Parameter'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_source',
            field=models.ManyToManyField(blank=True, related_name='project_data', to='parameters.DataSource'),
        ),
        migrations.AddField(
            model_name='project',
            name='params',
            field=models.ManyToManyField(blank=True, related_name='project_param', to='parameters.Parameter'),
        ),
    ]
