# Generated by Django 2.2.5 on 2020-10-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_auto_20201021_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
