# Generated by Django 2.2.5 on 2020-11-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_auto_20201104_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='BaseDim_Length',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='BaseDim_Mass',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='BaseDim_MonetaryUnit',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='BaseDim_Number',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='BaseDim_Time',
        ),
        migrations.AddField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('Probability', 'Probability'), ('Rate', 'Rate'), ('Cost', 'Cost'), ('Numeric Value', 'Numeric Value'), ('Integer Value', 'Integer Value'), ('Boolean Value', 'Boolean Value'), ('Numeric List', 'Numeric List'), ('Integer List', 'Integer List'), ('Boolean List', 'Boolean List')], default='Numeric Value', max_length=255, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
